### ISSUE TITLE
Cannot install with composer

### ISSUE THREAD

**Issue by olegstepura** [FriendsOfSymfony/FOSTwitterBundle#24] opened 2012-03-11 17:40 UTC
Error is:

```
Updating dependencies
PHP Warning:  assert(): Assertion failed in phar:///home/webdev/sites/composer.phar/src/Composer/DependencyResolver/Solver.php on line 2

Warning: assert(): Assertion failed in phar:///home/webdev/sites/composer.phar/src/Composer/DependencyResolver/Solver.php on line 2
PHP Fatal error:  Call to a member function getId() on a non-object in phar:///home/webdev/sites/composer.phar/src/Composer/DependencyResolver/Rule.php on line 2

Fatal error: Call to a member function getId() on a non-object in phar:///home/webdev/sites/composer.phar/src/Composer/DependencyResolver/Rule.php on line 2
```

However when I add this to composer.json, everything works

```
    "repositories":[
        {
            "type":"package",
            "package":{
                "name":"kertz/twitteroauth",
                "version":"dev-master",
                "source":{
                    "url":"git://github.com/kertz/twitteroauth.git",
                    "type":"git",
                    "reference":"origin/master"
                }
            }
        },
        {
            "type":"package",
            "package":{
                "name":"friendsofsymfony/twitter-bundle",
                "version":"dev-master",
                "source":{
                    "url":"git://github.com/FriendsOfSymfony/FOSTwitterBundle.git",
                    "type":"git",
                    "reference":"origin/master"
                },
                "autoload": {
                    "psr-0": { "FOS\\TwitterBundle": "" }
                },
                "target-dir": "FOS/TwitterBundle",
                "require": {
                    "php": ">=5.3.2",
                    "kertz/twitteroauth": "dev-master"
                }
            }
        },
```

**Comment by lsmith77** [comment] 2012-03-11 18:25
this looks more like a composer bug .. @Seldaek said there is likely already a report for this on composer/composer .. but if not it would be good to report it there ..

**Comment by olegstepura** [comment] 2012-03-11 18:26
I'm not sure which configuration item causes the issue

**Comment by Seldaek** [comment] 2012-03-11 18:34
Please report it with the whole composer.json to composer/composer - we will see if we can reproduce & hopefully fix. asserts should never fail so it's a clear indicator of a bug.

**Comment by stof** [comment] 2012-04-15 14:06
Closing as it looks like a composer bug (and you were defining your own packages anyway)

**Closed as completed by stof** 2012-04-15 14:06 UTC
